language: android
android:
  components:
  - platform-tools
  - build-tools
  - android-19
  - android-22
  - android-23
sudo: false
cache:
  directories:
  - node_modules
before_install:
  - nvm install 5.1 && nvm alias default 5.1 && nvm use 5.1
  - npm install --quiet -g npm cordova
  - openssl aes-256-cbc -k "$keystore_enc_password" -in simplerak.keystore.enc -out simplerak.keystore -d
before_script:
  - npm install --quiet
script:
  - npm run build
  - cordova build android --release
after_success:
  - export PATH=$(find /usr/local/android-sdk/ -name zipalign -type f| head -1 | sed -e 's/\/zipalign//g'):$PATH
  - export KEYSTORE=$(pwd)/simplerak.keystore
  - ls platforms/android/build/outputs/apk/
  - APK=platforms/android/build/outputs/apk/android-release npm run sign
  - md5sum platforms/android/build/outputs/apk/*.apk && sha512sum platforms/android/build/outputs/apk/*.apk
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: REgeIaHbBjMektIqH+sdlmdqtz9KCn5wUcPtamMvquwFUn676VtBqTwYAPUsrq46FojKM1t3unXjSdp1rwslijX0Q9NTZW0FOnkbfmUB4PwveSTFcr1oBd0h+APfYnSiw62RHW6+JjGrK0jNQLQAA35PTows4FKW8mIyzzDWFT+LklHoQ4NP3NNp2hqXmMbcsVkQtEdHhN2a+Kh3zFEnCzDeoQN7BqhJmHIeKR23cK0I9P4wAyJjPkvcFtb32D93TyN3ysBS6l4LNeYI5aAGdf5KKJez66Hipo3L3A03BTsIfMxSlPrhmw3REWje9xFxDUCvyH4E7WxjMo1oICJQ+N6VEUTHSb0OMMByTxz+3gxf9slydR5d23Uy4c6XFGBB6DLwa97cRgs7wM/k0XgfK7lwQg+20fs4IoesGp+6TqpfR9M4IgYjX2XEg2A5bF62dKJjVWWeCAQtWqRlgStKNpUSI27s786mHRQZdlPf2rJ8uyd5zUbhjJ2wCRJX08nVff4TGKDJJvLjvu+/nni4NjGrft1sxgBQIe29zPlJ7CTh29qRLNTbis/Uodi76YaQQV352/R9sowRIkKFGH34grvXgtiKbTPuvkhcN4XfUu7Dm+QCoS5C5u0etHUIo3hqRhq0po1HmIqkT7c6QGERKVFbpT5OwynYjzHYKmmrECc=
  file:
    - "platforms/android/build/outputs/apk/android-release-signed-aligned.apk"
  on:
    tags: true
