language: android
jdk:
  - oraclejdk8
android:
  components:
    - "1"
    - "2"
    - "3"
    - "32"
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

sudo: false
cache:
  directories:
  - node_modules
before_install:
  - nvm install 7 && nvm alias default 7 && nvm use 7
  - npm install --quiet -g npm cordova
  - openssl aes-256-cbc -k "$keystore_enc_password" -in simplerak.keystore.enc -out simplerak.keystore -d
before_script:
  - npm install --quiet
script:
  - npm run build
  - cordova prepare android
  - rm -Rf platforms/android/res/drawable-* platforms/android/res/mipmap-*
  - mkdir -p platforms/android/res/mipmap-mdpi-v4 && cp www/img/logo.png platforms/android/res/mipmap-mdpi-v4/icon.png
  - cordova build android --release
after_success:
  - export PATH=$(find /usr/local/android-sdk/ -name zipalign -type f| head -1 | sed -e 's/\/zipalign//g'):$PATH
  - export KEYSTORE=$(pwd)/simplerak.keystore
  - ls platforms/android/build/outputs/apk/
  - APK=platforms/android/build/outputs/apk/android-release npm run sign
  - md5sum platforms/android/build/outputs/apk/*.apk && sha512sum platforms/android/build/outputs/apk/*.apk
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: K6W6U04Gyf0wZP1TzoIQ24vnUuWdWbj9clb0XD9CrZteWI2alkFIX34BSsBWvWOu7vROulbCRcfyrAlPZzl6RZNtV/orIfN3m+4ax+VnVoazU0UdRWf8VCg8sCtNUx0HMhYCG6++3Odt/HnMQACMYwr/xDy5j8k2hgQQkVFGwYI=
  file:
    - "platforms/android/build/outputs/apk/android-release-signed-aligned.apk"
  on:
    tags: true
